# Generated by Django 2.2.2 on 2019-07-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='quesion',
            new_name='question',
        ),
    ]
